import { Difficulty, ExplanationStyle } from './types';

export const APP_TITLE = "Quiz AI";

export const LOCALIZED_STRINGS = {
  en: {
    APP_TITLE: "Quiz AI",
    name: "Name",
    tagline: "Generate engaging quizzes from your documents instantly.",
    uploadFile: "Upload Document",
    uploadSpreadsheet: "Or Upload Spreadsheet",
    selectDifficulty: "Select Difficulty Level",
    generateQuiz: "Generate Quiz",
    generating: "Generating Quiz...",
    favorites: "Favorites",
    goBack: "Go Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    correct: "Correct!",
    incorrect: "Incorrect. The correct answer is:",
    addToFavorites: "Add to Favorites",
    removeFromFavorites: "Remove from Favorites",
    noFavorites: "You haven't saved any favorite questions yet.",
    exportToPdf: "Export as PDF",
    exportToExcel: "Export as Excel",
    uploadInstructions: "Upload a document or an image (.png, .jpg) for AI-powered OCR and question generation.",
    spreadsheetInstructions: "Alternatively, upload an Excel/CSV with columns: Question, Option1, Option2, Option3, Option4, CorrectAnswerIndex (0-3).",
    errorTitle: "An Error Occurred",
    errorParsingFile: "Could not read or parse the file. Please check the format.",
    errorGeneratingQuiz: "Failed to generate quiz. Please try again.",
    errorGradingAnswer: "Could not grade your answer. Please check your API key configuration.",
    [Difficulty.Easy]: "Easy",
    [Difficulty.Medium]: "Medium",
    [Difficulty.Hard]: "Hard",
    viewFavorites: "View Favorites",
    startNewQuiz: "Start New Quiz",
    question: "Question",
    yourAnswer: "Your Answer",
    correctAnswer: "Correct Answer",
    examTitle: "Quiz Exam",
    downloadTemplate: "Download Template",
    justification: "Justification",
    finishQuiz: "Finish Quiz",
    quizComplete: "Quiz Complete!",
    yourScore: "Your Score",
    restartQuiz: "Start a New Quiz",
    timeUp: "Time's up! The correct answer is:",
    timeUpWritten: "Time's up! An empty answer was submitted.",
    retakeIncorrect: "Retake Incorrect Questions",
    correctAnswers: "Correct Answers",
    incorrectAnswers: "Incorrect Answers",
    history: "History",
    noHistory: "You haven't completed any quizzes yet.",
    viewDetails: "View Details",
    score: "Score",
    completedOn: "Completed on",
    quizDetails: "Quiz Details",
    backToHistory: "Back to History",
    editAndRetake: "Edit & Retake",
    quizEditorTitle: "Quiz Editor",
    startEditedQuiz: "Start Edited Quiz",
    unanswered: "Unanswered",
    readAloud: "Read Aloud",
    stopReading: "Stop Reading",
    explainBetter: "Explain this better",
    explanation: "Explanation",
    gettingExplanation: "Getting a better explanation...",
    close: "Close",
    errorGettingExplanation: "Sorry, I couldn't get a better explanation right now.",
    option: "Option",
    saveAndExit: "Save & Exit",
    enterQuizName: "Enter a name for your quiz",
    save: "Save",
    cancel: "Cancel",
    untitledQuiz: "Untitled Quiz",
    areYouSureAbandon: "You have a quiz in progress. It will be automatically saved in your paused history so you don't lose progress. Do you want to start a new one?",
    paused: "Paused",
    resume: "Resume",
    delete: "Delete",
    rename: "Rename",
    moreActions: "More actions",
    generateReport: "Generate Report",
    generateEvaluation: "Generate Evaluation Sheet",
    generateQuizWithKey: "Generate Exam with Key",
    answerKey: "Answer Key",
    date: "Date",
    flashcards: "Flashcards",
    studyWithFlashcards: "Study with Flashcards",
    cardOf: "Card {current} of {total}",
    flip: "Flip",
    createYourQuiz: "Create Your Quiz",
    enableTimer: "Enable Timer per Question",
    welcomeTitle: "Welcome to Quiz AI",
    welcomeFeature1Title: "Upload Any Document",
    welcomeFeature1Desc: "Use text files, spreadsheets, or even images. Our AI will analyze the content and create questions.",
    welcomeFeature2Title: "Save & Organize",
    welcomeFeature2Desc: "Keep your favorite questions saved for later, and export them in PDF or Excel format anytime.",
    welcomeFeature3Title: "Track Your Progress",
    welcomeFeature3Desc: "Review your quiz history, see detailed results, and retake quizzes to improve your knowledge.",
    resumeQuizTitle: "Resume Quiz?",
    resumeQuizText: "You have a quiz in progress. Do you want to continue where you left off?",
    continueQuiz: "Continue Quiz",
    abandonQuiz: "Abandon & Start New",
    statistics: "Statistics",
    interfaceSettings: "Interface Settings",
    themeColor: "Theme Color",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    settings: "Settings",
    noStatistics: "Complete a quiz to see your statistics here.",
    overallPerformance: "Overall Performance",
    averageScore: "Average Score",
    quizzesCompleted: "Quizzes Completed",
    performanceByDifficulty: "Performance by Difficulty",
    quizCompletionTrend: "Quiz Completion Trend",
    quizzesPerMonth: "Quizzes per month (last 6)",
    createManuallyTitle: "Or use a custom prompt",
    createManuallyDesc: "Copy the prompt below to generate questions with a specific column format. Paste it into your document and upload, or use it in your preferred AI tool.",
    copyPrompt: "Copy Prompt",
    copied: "Copied!",
    promptToCopy: "GENERATE QUESTIONS WITH COLUMN FORMAT: Question, Option1, Option2, Option3, Option4, CorrectAnswerIndex (0-3), Justification",
    status: "Status",
    completed: "Completed",
    inProgress: "In Progress",
    downloadBackupExcel: "Download Backup (Excel)",
    summary: "Summary",
    result: "Result",
    regenerate: "Regenerate",
    selectExplanationStyle: "Select Explanation Style",
    [ExplanationStyle.Tecnica]: "Technical",
    [ExplanationStyle.Cientifica]: "Scientific",
    [ExplanationStyle.Academica]: "Academic",
    [ExplanationStyle.Didactica]: "Didactic or pedagogical",
    [ExplanationStyle.Analitica]: "Analytical",
    [ExplanationStyle.Comparativa]: "Comparative",
    [ExplanationStyle.Practica]: "Practical or applied",
    [ExplanationStyle.Descriptiva]: "Descriptive",
    [ExplanationStyle.Causal]: "Causal",
    [ExplanationStyle.Funcional]: "Functional",
    [ExplanationStyle.Teleologica]: "Teleological (by purpose)",
    [ExplanationStyle.Historica]: "Historical",
    [ExplanationStyle.Filosofica]: "Philosophical",
    quizMode: "Quiz Mode",
    MultipleChoice: "Multiple Choice",
    Written: "Written Response",
    submitAnswer: "Submit Answer",
    aiGrading: "Grading with AI...",
    yourWrittenAnswer: "Your Written Answer",
    aiFeedback: "AI Feedback",
    similarityScore: "Similarity Score",
    correctAnswerText: "Correct Answer for Reference",
    specificInstructions: "Specific Instructions",
    optional: "Optional",
    promptPlaceholder: "e.g., Focus on chapter 3, create questions about historical context...",
    selectAll: "Select All",
    itemsSelected: "{count} items selected",
    deleteSelected: "Delete Selected",
    confirmDeleteSelected: "Are you sure you want to delete {count} selected quizzes? This action cannot be undone.",
    saveExplanation: "Save Explanation",
    explanationSaved: "Saved!",
    explanationColumn: "Explanation {n}",
    autoReadAloud: "Automatic Read Aloud",
    soundEffects: "Sound Effects",
    speechInputEnabled: "Voice Answer Mode",
    speechInputDesc: "Enable microphone to dictate open-ended answers",
    speechInputMicActive: "Listening... Speak now.",
    speechInputUnsupported: "Voice recognition not supported in this browser.",
    voiceAssistantMode: "Hands-Free Voice Assistant",
    voiceAssistantDesc: "The assistant reads questions, listens to your answer, and advances automatically without touching the screen.",
    assistantAiModel: "Hands-Free AI Model",
    assistantAiModelDesc: "Choose the model used to interpret, grade, and explain hands-free answers.",
    assistantStatusReading: "Assistant: Reading question...",
    assistantStatusListening: "Assistant: Listening to your answer...",
    assistantStatusGrading: "Assistant: Grading answer...",
    assistantStatusFeedback: "Assistant: Explaining score...",
    playAudio: "Play Audio",
    stopAudio: "Stop Audio",
    notificationTitle: "Notifications",
    notificationNew: "{count} new",
    noNotifications: "No notifications.",
    correctNotification: "Correct!",
    incorrectFeedback: "Feedback",
    educationalChallenge: "Educational Challenge!",
    challengeReported: "Quiz Reported!",
    reportedBy: "@{sender} reported: '{name}'",
    reason: "Reason: {reason}",
    accept: "Accept",
    panelAdmin: "Admin Panel",
    viewHistory: "View History",
    read: "Read",
    hello: "Hello,",
    exit: "Exit",
    logIn: "Log In",
    successfulChallengers: "Successful Challengers ({count})",
    noChallengersYet: "Nobody has completed this challenge yet! Be the first to conquer it.",
    mustLoginToStart: "You must log in or register to start this challenge. Do you want to go to login?",
    acceptChallenge: "Accept Challenge",
    welcomeUser: "Welcome, @{name}!",
    preparingEnvironment: "Preparing your educational environment",
    farewellUser: "See you soon, @{name}!",
    loggingOutSafely: "Logging out safely",
    menu: "Menu",
    myAccount: "My Account",
    closeSession: "Close Session",
    settingsText: "Settings",
    navLanding: "Home",
    navPublic: "Public Challenges",
    navFavorites: "Favorites ({count})",
    navHistory: "History",
    navStatistics: "Statistics",
    navGenerator: "Create Quiz",
    continueQuizNav: "Continue Quiz",
    landingTitle: "Transform Any Content Into Interactive Quizzes",
    landingTagline: "QuizAI is an advanced platform that allows you to upload documents, spreadsheets, or images of your notes to create educational challenges with in-depth explanations and AI answer grading.",
    landingButtonCreate: "Go to Create Quizzes",
    landingButtonLogin: "Get Started Now - Log In",
    whatCanYouDo: "What can you do with QuizAI?",
    whatCanYouDoDesc: "Explore the tools we have designed to take your learning to the next level.",
    feature1Title: "AI Generation",
    feature1Desc: "Upload text files, photos of your notes, or Excel templates and generate structured quizzes instantly.",
    feature2Title: "Written Mode & AI",
    feature2Desc: "Answer questions in your own words. Gemini will evaluate the meaning and give you format grades and justifications.",
    feature3Title: "Public Challenges",
    feature3Desc: "Share your quizzes with the public so other students can demonstrate their knowledge and appear in your challenge.",
    feature4Title: "History & Flashcards",
    feature4Desc: "Save your favorites, review detailed statistics of your learning, and study your mistakes using dynamic flashcards.",
    socialNetworks: "Social Networks",
    socialNetworksDesc: "Follow our official SV GROUP channels to learn about news, projects, and technological innovations.",
    createdBy: "Created by: ",
    questionsCount: "Questions",
    timeLimit: "Time Limit",
    yes: "Yes",
    no: "No"
  },
  es: {
    APP_TITLE: "Quiz AI",
    name: "Nombre",
    tagline: "Genera cuestionarios atractivos a partir de tus documentos al instante.",
    uploadFile: "Subir Documento",
    uploadSpreadsheet: "O Subir Hoja de Cálculo",
    selectDifficulty: "Seleccionar Nivel de Dificultad",
    generateQuiz: "Generar Cuestionario",
    generating: "Generando Cuestionario...",
    favorites: "Favoritos",
    goBack: "Regresar",
    next: "Siguiente",
    previous: "Anterior",
    submit: "Enviar",
    correct: "¡Correcto!",
    incorrect: "Incorrecto. La respuesta correcta es:",
    addToFavorites: "Añadir a Favoritos",
    removeFromFavorites: "Quitar de Favoritos",
    noFavorites: "Aún no has guardado ninguna pregunta favorita.",
    exportToPdf: "Exportar como PDF",
    exportToExcel: "Exportar como Excel",
    uploadInstructions: "Sube un documento o una imagen (.png, .jpg) para OCR y generación de preguntas con IA.",
    spreadsheetInstructions: "Alternativamente, sube un Excel/CSV con las columnas: Pregunta, Opcion1, Opcion2, Opcion3, Opcion4, IndiceRespuestaCorrecta (0-3).",
    errorTitle: "Ocurrió un Error",
    errorParsingFile: "No se pudo leer o analizar el archivo. Por favor, revisa el formato.",
    errorGeneratingQuiz: "No se pudo generar el cuestionario. Por favor, inténtalo de nuevo.",
    errorGradingAnswer: "No se pudo calificar tu respuesta. Por favor, verifica la configuración de tu clave de API.",
    [Difficulty.Easy]: "Fácil",
    [Difficulty.Medium]: "Medio",
    [Difficulty.Hard]: "Difícil",
    viewFavorites: "Ver Favoritos",
    startNewQuiz: "Nuevo Cuestionario",
    question: "Pregunta",
    yourAnswer: "Tu Respuesta",
    correctAnswer: "Respuesta Correcta",
    examTitle: "Examen del Cuestionario",
    downloadTemplate: "Descargar Plantilla",
    justification: "Justificación",
    finishQuiz: "Finalizar Cuestionario",
    quizComplete: "¡Cuestionario Completo!",
    yourScore: "Tu Puntuación",
    restartQuiz: "Empezar un Nuevo Cuestionario",
    timeUp: "¡Se acabó el tiempo! La respuesta correcta es:",
    timeUpWritten: "¡Se acabó el tiempo! Se ha enviado una respuesta vacía.",
    retakeIncorrect: "Repetir Preguntas Incorrectas",
    correctAnswers: "Respuestas Correctas",
    incorrectAnswers: "Respuestas Incorrectas",
    history: "Historial",
    noHistory: "Aún no has completado ningún cuestionario.",
    viewDetails: "Ver Detalles",
    score: "Puntuación",
    completedOn: "Completado el",
    quizDetails: "Detalles del Cuestionario",
    backToHistory: "Volver al Historial",
    editAndRetake: "Editar y Repetir",
    quizEditorTitle: "Editor de Cuestionario",
    startEditedQuiz: "Empezar Cuestionario Editado",
    unanswered: "Sin responder",
    readAloud: "Leer en voz alta",
    stopReading: "Detener lectura",
    explainBetter: "Explícamelo mejor",
    explanation: "Explicación",
    gettingExplanation: "Obteniendo una mejor explicación...",
    close: "Cerrar",
    errorGettingExplanation: "Lo siento, no pude obtener una mejor explicación en este momento.",
    option: "Opción",
    saveAndExit: "Guardar y Salir",
    enterQuizName: "Introduce un nombre para tu cuestionario",
    save: "Guardar",
    cancel: "Cancelar",
    untitledQuiz: "Cuestionario sin título",
    areYouSureAbandon: "Tienes un cuestionario en curso. Se guardará automáticamente en tu historial de retos en pausa para que no pierdas tu avance. ¿Quieres empezar uno nuevo?",
    paused: "En Pausa",
    resume: "Continuar",
    delete: "Eliminar",
    rename: "Renombrar",
    moreActions: "Más acciones",
    generateReport: "Generar Reporte",
    generateEvaluation: "Generar Hoja de Evaluación",
    generateQuizWithKey: "Generar Examen con Clave",
    answerKey: "Clave de Respuestas",
    date: "Fecha",
    flashcards: "Tarjetas de Estudio",
    studyWithFlashcards: "Estudiar con Tarjetas",
    cardOf: "Tarjeta {current} de {total}",
    flip: "Voltear",
    createYourQuiz: "Crea Tu Cuestionario",
    enableTimer: "Activar Temporizador por Pregunta",
    welcomeTitle: "Bienvenido a Quiz AI",
    welcomeFeature1Title: "Sube Cualquier Documento",
    welcomeFeature1Desc: "Usa archivos de texto, hojas de cálculo o incluso imágenes. Nuestra IA analizará el contenido y creará preguntas.",
    welcomeFeature2Title: "Guarda y Organiza",
    welcomeFeature2Desc: "Mantén tus preguntas favoritas guardadas para más tarde y expórtalas en formato PDF o Excel en cualquier momento.",
    welcomeFeature3Title: "Sigue Tu Progreso",
    welcomeFeature3Desc: "Revisa tu historial de cuestionarios, ve resultados detallados y repite los cuestionarios para mejorar tus conocimientos.",
    resumeQuizTitle: "¿Continuar Cuestionario?",
    resumeQuizText: "Tienes un cuestionario en progreso. ¿Quieres continuar donde lo dejaste?",
    continueQuiz: "Continuar Cuestionario",
    abandonQuiz: "Abandonar y Empezar de Nuevo",
    statistics: "Estadísticas",
    interfaceSettings: "Configuración de Interfaz",
    themeColor: "Color del Tema",
    appearance: "Apariencia",
    light: "Claro",
    dark: "Oscuro",
    settings: "Ajustes",
    noStatistics: "Completa un cuestionario para ver tus estadísticas aquí.",
    overallPerformance: "Rendimento General",
    averageScore: "Puntuación Media",
    quizzesCompleted: "Cuestionarios Completados",
    performanceByDifficulty: "Rendimiento por Dificultad",
    quizCompletionTrend: "Tendencia de Finalización",
    quizzesPerMonth: "Cuestionarios por mes (últimos 6)",
    createManuallyTitle: "O usa un prompt personalizado",
    createManuallyDesc: "Copia el siguiente prompt para generar preguntas con un formato de columnas específico. Pégalo en tu documento y súbelo, o úsalo en tu herramienta de IA preferida.",
    copyPrompt: "Copiar Prompt",
    copied: "¡Copiado!",
    promptToCopy: "GENERAME PREGUNTAS CON FORMATO DE TABLA CON COLUMNAS: Pregunta, Opcion1, Opcion2, Opcion3, Opcion4, IndiceRespuestaCorrecta (0-3), Justificación",
    status: "Estado",
    completed: "Completado",
    inProgress: "En Progreso",
    downloadBackupExcel: "Descargar Respaldo (Excel)",
    summary: "Resumen",
    result: "Resultado",
    regenerate: "Regenerar",
    selectExplanationStyle: "Seleccionar Estilo de Explicación",
    [ExplanationStyle.Tecnica]: "Técnica",
    [ExplanationStyle.Cientifica]: "Científica",
    [ExplanationStyle.Academica]: "Académica",
    [ExplanationStyle.Didactica]: "Didáctica o pedagógica",
    [ExplanationStyle.Analitica]: "Analítica",
    [ExplanationStyle.Comparativa]: "Comparativa",
    [ExplanationStyle.Practica]: "Práctica o aplicada",
    [ExplanationStyle.Descriptiva]: "Descriptiva",
    [ExplanationStyle.Causal]: "Causal",
    [ExplanationStyle.Funcional]: "Funcional",
    [ExplanationStyle.Teleologica]: "Teleológica (por finalidad)",
    [ExplanationStyle.Historica]: "Histórica",
    [ExplanationStyle.Filosofica]: "Filosófica",
    quizMode: "Modo de Cuestionario",
    MultipleChoice: "Opción Múltiple",
    Written: "Respuesta Escrita",
    submitAnswer: "Enviar Respuesta",
    aiGrading: "Calificando con IA...",
    yourWrittenAnswer: "Tu Respuesta Escrita",
    aiFeedback: "Comentarios de la IA",
    similarityScore: "Puntaje de Similitud",
    correctAnswerText: "Respuesta Correcta de Referencia",
    specificInstructions: "Instrucciones Específicas",
    optional: "Opcional",
    promptPlaceholder: "Ej: Enfócate en el capítulo 3, crea preguntas sobre el contexto histórico...",
    selectAll: "Seleccionar todo",
    itemsSelected: "{count} elementos seleccionados",
    deleteSelected: "Eliminar seleccionados",
    confirmDeleteSelected: "¿Estás seguro de que quieres eliminar {count} cuestionarios seleccionados? Esta acción no se puede deshacer.",
    saveExplanation: "Guardar Explicación",
    explanationSaved: "¡Guardada!",
    explanationColumn: "Explicación {n}",
    autoReadAloud: "Lectura de voz automática",
    soundEffects: "Efectos de sonido",
    speechInputEnabled: "Modo Responder por Voz",
    speechInputDesc: "Activa el micrófono para dictar tus respuestas escritas",
    speechInputMicActive: "Escuchando... Habla ahora.",
    speechInputUnsupported: "El reconocimiento de voz no está soportado en este navegador.",
    voiceAssistantMode: "Asistente de Voz Manos Libres",
    voiceAssistantDesc: "El asistente lee las preguntas, escucha tu respuesta y avanza de forma automática sin tocar la pantalla.",
    assistantAiModel: "Modelo de IA del asistente manos libres",
    assistantAiModelDesc: "Elige el modelo que interpreta, califica y explica las respuestas manos libres.",
    assistantStatusReading: "Asistente: Leyendo pregunta...",
    assistantStatusListening: "Asistente: Escuchando tu respuesta...",
    assistantStatusGrading: "Asistente: Calificando respuesta...",
    assistantStatusFeedback: "Asistente: Explicando resultado...",
    playAudio: "Reproducir audio",
    stopAudio: "Detener lectura",
    notificationTitle: "Notificaciones",
    notificationNew: "{count} nuevas",
    noNotifications: "Sin notificaciones.",
    correctNotification: "¡Correcto!",
    incorrectFeedback: "Feedback",
    educationalChallenge: "¡Reto Educativo!",
    challengeReported: "¡Cuestionario Reportado!",
    reportedBy: "@{sender} denunció: '{name}'",
    reason: "Motivo: {reason}",
    accept: "Aceptar",
    panelAdmin: "Panel Admin",
    viewHistory: "Ver Historial",
    read: "Leído",
    hello: "Hola,",
    exit: "Salir",
    logIn: "Iniciar Sesión",
    successfulChallengers: "Retadores Exitosos ({count})",
    noChallengersYet: "¡Nadie ha completado este reto todavía! Sé el primero en conquistarlo.",
    mustLoginToStart: "Debes iniciar sesión o registrarte para empezar este reto. ¿Quieres ir al login?",
    acceptChallenge: "Aceptar Reto",
    welcomeUser: "¡Bienvenido, @{name}!",
    preparingEnvironment: "Preparando tu entorno educativo",
    farewellUser: "¡Hasta pronto, @{name}!",
    loggingOutSafely: "Cerrando sesión de forma segura",
    menu: "Menú",
    myAccount: "Mi Cuenta",
    closeSession: "Cerrar Sesión",
    settingsText: "Configuración",
    navLanding: "Inicio",
    navPublic: "Retos Públicos",
    navFavorites: "Favoritos ({count})",
    navHistory: "Historial",
    navStatistics: "Estadísticas",
    navGenerator: "Nuevo Cuestionario",
    continueQuizNav: "Continuar Cuestionario",
    landingTitle: "Transforma Cualquier Contenido en Cuestionarios Interactivos",
    landingTagline: "QuizAI es una plataforma avanzada que te permite subir documentos, hojas de cálculo o imágenes de tus apuntes para crear retos educativos con explicaciones profundas e IA calificadora de respuestas.",
    landingButtonCreate: "Ir a Crear Cuestionarios",
    landingButtonLogin: "Comenzar Ahora - Iniciar Sesión",
    whatCanYouDo: "¿Qué puedes hacer con QuizAI?",
    whatCanYouDoDesc: "Explora las herramientas que hemos diseñado para llevar tu aprendizaje al siguiente nivel.",
    feature1Title: "Generación con IA",
    feature1Desc: "Sube archivos de texto, fotos de tus apuntes o plantillas Excel y genera cuestionarios estructurados al instante.",
    feature2Title: "Modo Escrito e IA",
    feature2Desc: "Responde preguntas con tus palabras. Gemini evaluará el significado y te dará notas y justificaciones formativas.",
    feature3Title: "Retos Públicos",
    feature3Desc: "Comparte tus cuestionarios con el público para que otros alumnos demuestren su conocimiento y aparezcan en tu reto.",
    feature4Title: "Historial y Flashcards",
    feature4Desc: "Guarda tus favoritos, repasa estadísticas detalladas de tu aprendizaje y estudia tus errores usando flashcards dinámicas.",
    socialNetworks: "Redes Sociales",
    socialNetworksDesc: "Sigue nuestros canales oficiales de SV GROUP para enterarte de novedades, proyectos e innovaciones tecnológicas.",
    createdBy: "Creado por: ",
    questionsCount: "Preguntas",
    timeLimit: "Límite de Tiempo",
    yes: "Sí",
    no: "No"
  }
};
