import { Difficulty, ExplanationStyle } from './types';

export const APP_TITLE = "AI Quiz Generator Pro";

export const LOCALIZED_STRINGS = {
  en: {
    APP_TITLE: "AI Quiz Generator Pro",
    name: "Name",
    tagline: "Generate engaging quizzes from your documents instantly.",
    uploadFile: "Upload Document",
    uploadSpreadsheet: "Or Upload Spreadsheet",
    selectDifficulty: "Select Difficulty Level",
    generateQuiz: "Generate Quiz",
    generating: "Generating Quiz...",
    favorites: "Favorites",
    goBack: "Go Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    correct: "Correct!",
    incorrect: "Incorrect. The correct answer is:",
    addToFavorites: "Add to Favorites",
    removeFromFavorites: "Remove from Favorites",
    noFavorites: "You haven't saved any favorite questions yet.",
    exportToPdf: "Export as PDF",
    exportToExcel: "Export as Excel",
    uploadInstructions: "Upload a document or an image (.png, .jpg) for AI-powered OCR and question generation.",
    spreadsheetInstructions: "Alternatively, upload an Excel/CSV with columns: Question, Option1, Option2, Option3, Option4, CorrectAnswerIndex (0-3).",
    errorTitle: "An Error Occurred",
    errorParsingFile: "Could not read or parse the file. Please check the format.",
    errorGeneratingQuiz: "Failed to generate quiz. Please try again.",
    [Difficulty.Easy]: "Easy",
    [Difficulty.Medium]: "Medium",
    [Difficulty.Hard]: "Hard",
    viewFavorites: "View Favorites",
    startNewQuiz: "Start New Quiz",
    question: "Question",
    yourAnswer: "Your Answer",
    correctAnswer: "Correct Answer",
    examTitle: "Quiz Exam",
    downloadTemplate: "Download Template",
    justification: "Justification",
    finishQuiz: "Finish Quiz",
    quizComplete: "Quiz Complete!",
    yourScore: "Your Score",
    restartQuiz: "Start a New Quiz",
    timeUp: "Time's up! The correct answer is:",
    timeUpWritten: "Time's up! An empty answer was submitted.",
    retakeIncorrect: "Retake Incorrect Questions",
    correctAnswers: "Correct Answers",
    incorrectAnswers: "Incorrect Answers",
    history: "History",
    noHistory: "You haven't completed any quizzes yet.",
    viewDetails: "View Details",
    score: "Score",
    completedOn: "Completed on",
    quizDetails: "Quiz Details",
    backToHistory: "Back to History",
    editAndRetake: "Edit & Retake",
    quizEditorTitle: "Quiz Editor",
    startEditedQuiz: "Start Edited Quiz",
    unanswered: "Unanswered",
    readAloud: "Read Aloud",
    stopReading: "Stop Reading",
    explainBetter: "Explain this better",
    explanation: "Explanation",
    gettingExplanation: "Getting a better explanation...",
    close: "Close",
    errorGettingExplanation: "Sorry, I couldn't get a better explanation right now.",
    option: "Option",
    saveAndExit: "Save & Exit",
    enterQuizName: "Enter a name for your quiz",
    save: "Save",
    cancel: "Cancel",
    untitledQuiz: "Untitled Quiz",
    areYouSureAbandon: "You have a quiz in progress. Are you sure you want to start a new one and abandon the current one?",
    paused: "Paused",
    resume: "Resume",
    delete: "Delete",
    rename: "Rename",
    moreActions: "More actions",
    generateReport: "Generate Report",
    generateEvaluation: "Generate Evaluation Sheet",
    generateQuizWithKey: "Generate Exam with Key",
    answerKey: "Answer Key",
    date: "Date",
    flashcards: "Flashcards",
    studyWithFlashcards: "Study with Flashcards",
    cardOf: "Card {current} of {total}",
    flip: "Flip",
    createYourQuiz: "Create Your Quiz",
    enableTimer: "Enable Timer per Question",
    welcomeTitle: "Welcome to AI Quiz Generator Pro",
    welcomeFeature1Title: "Upload Any Document",
    welcomeFeature1Desc: "Use text files, spreadsheets, or even images. Our AI will analyze the content and create questions.",
    welcomeFeature2Title: "Save & Organize",
    welcomeFeature2Desc: "Keep your favorite questions saved for later, and export them in PDF or Excel format anytime.",
    welcomeFeature3Title: "Track Your Progress",
    welcomeFeature3Desc: "Review your quiz history, see detailed results, and retake quizzes to improve your knowledge.",
    resumeQuizTitle: "Resume Quiz?",
    resumeQuizText: "You have a quiz in progress. Do you want to continue where you left off?",
    continueQuiz: "Continue Quiz",
    abandonQuiz: "Abandon & Start New",
    statistics: "Statistics",
    interfaceSettings: "Interface Settings",
    themeColor: "Theme Color",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    settings: "Settings",
    noStatistics: "Complete a quiz to see your statistics here.",
    overallPerformance: "Overall Performance",
    averageScore: "Average Score",
    quizzesCompleted: "Quizzes Completed",
    performanceByDifficulty: "Performance by Difficulty",
    quizCompletionTrend: "Quiz Completion Trend",
    quizzesPerMonth: "Quizzes per month (last 6)",
    createManuallyTitle: "Or use a custom prompt",
    createManuallyDesc: "Copy the prompt below to generate questions with a specific column format. Paste it into your document and upload, or use it in your preferred AI tool.",
    copyPrompt: "Copy Prompt",
    copied: "Copied!",
    promptToCopy: "GENERATE QUESTIONS WITH COLUMN FORMAT: Question, Option1, Option2, Option3, Option4, CorrectAnswerIndex (0-3), Justification",
    status: "Status",
    completed: "Completed",
    inProgress: "In Progress",
    downloadBackupExcel: "Download Backup (Excel)",
    summary: "Summary",
    result: "Result",
    regenerate: "Regenerate",
    selectExplanationStyle: "Select Explanation Style",
    [ExplanationStyle.Tecnica]: "Technical",
    [ExplanationStyle.Cientifica]: "Scientific",
    [ExplanationStyle.Academica]: "Academic",
    [ExplanationStyle.Didactica]: "Didactic or pedagogical",
    [ExplanationStyle.Analitica]: "Analytical",
    [ExplanationStyle.Comparativa]: "Comparative",
    [ExplanationStyle.Practica]: "Practical or applied",
    [ExplanationStyle.Descriptiva]: "Descriptive",
    [ExplanationStyle.Causal]: "Causal",
    [ExplanationStyle.Funcional]: "Functional",
    [ExplanationStyle.Teleologica]: "Teleological (by purpose)",
    [ExplanationStyle.Historica]: "Historical",
    [ExplanationStyle.Filosofica]: "Philosophical",
    quizMode: "Quiz Mode",
    MultipleChoice: "Multiple Choice",
    Written: "Written Response",
    submitAnswer: "Submit Answer",
    aiGrading: "Grading with AI...",
    yourWrittenAnswer: "Your Written Answer",
    aiFeedback: "AI Feedback",
    similarityScore: "Similarity Score",
    correctAnswerText: "Correct Answer for Reference",
    specificInstructions: "Specific Instructions",
    optional: "Optional",
    promptPlaceholder: "e.g., Focus on chapter 3, create questions about historical context...",
    selectAll: "Select All",
    itemsSelected: "{count} items selected",
    deleteSelected: "Delete Selected",
    confirmDeleteSelected: "Are you sure you want to delete {count} selected quizzes? This action cannot be undone.",
    saveExplanation: "Save Explanation",
    explanationSaved: "Saved!",
    explanationColumn: "Explanation {n}",
  },
  es: {
    APP_TITLE: "AI Quiz Generator Pro",
    name: "Nombre",
    tagline: "Genera cuestionarios atractivos a partir de tus documentos al instante.",
    uploadFile: "Subir Documento",
    uploadSpreadsheet: "O Subir Hoja de Cálculo",
    selectDifficulty: "Seleccionar Nivel de Dificultad",
    generateQuiz: "Generar Cuestionario",
    generating: "Generando Cuestionario...",
    favorites: "Favoritos",
    goBack: "Regresar",
    next: "Siguiente",
    previous: "Anterior",
    submit: "Enviar",
    correct: "¡Correcto!",
    incorrect: "Incorrecto. La respuesta correcta es:",
    addToFavorites: "Añadir a Favoritos",
    removeFromFavorites: "Quitar de Favoritos",
    noFavorites: "Aún no has guardado ninguna pregunta favorita.",
    exportToPdf: "Exportar como PDF",
    exportToExcel: "Exportar como Excel",
    uploadInstructions: "Sube un documento o una imagen (.png, .jpg) para OCR y generación de preguntas con IA.",
    spreadsheetInstructions: "Alternativamente, sube un Excel/CSV con las columnas: Pregunta, Opcion1, Opcion2, Opcion3, Opcion4, IndiceRespuestaCorrecta (0-3).",
    errorTitle: "Ocurrió un Error",
    errorParsingFile: "No se pudo leer o analizar el archivo. Por favor, revisa el formato.",
    errorGeneratingQuiz: "No se pudo generar el cuestionario. Por favor, inténtalo de nuevo.",
    [Difficulty.Easy]: "Fácil",
    [Difficulty.Medium]: "Medio",
    [Difficulty.Hard]: "Difícil",
    viewFavorites: "Ver Favoritos",
    startNewQuiz: "Nuevo Cuestionario",
    question: "Pregunta",
    yourAnswer: "Tu Respuesta",
    correctAnswer: "Respuesta Correcta",
    examTitle: "Examen del Cuestionario",
    downloadTemplate: "Descargar Plantilla",
    justification: "Justificación",
    finishQuiz: "Finalizar Cuestionario",
    quizComplete: "¡Cuestionario Completo!",
    yourScore: "Tu Puntuación",
    restartQuiz: "Empezar un Nuevo Cuestionario",
    timeUp: "¡Se acabó el tiempo! La respuesta correcta es:",
    timeUpWritten: "¡Se acabó el tiempo! Se ha enviado una respuesta vacía.",
    retakeIncorrect: "Repetir Preguntas Incorrectas",
    correctAnswers: "Respuestas Correctas",
    incorrectAnswers: "Respuestas Incorrectas",
    history: "Historial",
    noHistory: "Aún no has completado ningún cuestionario.",
    viewDetails: "Ver Detalles",
    score: "Puntuación",
    completedOn: "Completado el",
    quizDetails: "Detalles del Cuestionario",
    backToHistory: "Volver al Historial",
    editAndRetake: "Editar y Repetir",
    quizEditorTitle: "Editor de Cuestionario",
    startEditedQuiz: "Empezar Cuestionario Editado",
    unanswered: "Sin responder",
    readAloud: "Leer en voz alta",
    stopReading: "Detener lectura",
    explainBetter: "Explícamelo mejor",
    explanation: "Explicación",
    gettingExplanation: "Obteniendo una mejor explicación...",
    close: "Cerrar",
    errorGettingExplanation: "Lo siento, no pude obtener una mejor explicación en este momento.",
    option: "Opción",
    saveAndExit: "Guardar y Salir",
    enterQuizName: "Introduce un nombre para tu cuestionario",
    save: "Guardar",
    cancel: "Cancelar",
    untitledQuiz: "Cuestionario sin título",
    areYouSureAbandon: "Tienes un cuestionario en curso. ¿Estás seguro de que quieres empezar uno nuevo y abandonar el actual?",
    paused: "En Pausa",
    resume: "Continuar",
    delete: "Eliminar",
    rename: "Renombrar",
    moreActions: "Más acciones",
    generateReport: "Generar Reporte",
    generateEvaluation: "Generar Hoja de Evaluación",
    generateQuizWithKey: "Generar Examen con Clave",
    answerKey: "Clave de Respuestas",
    date: "Fecha",
    flashcards: "Tarjetas de Estudio",
    studyWithFlashcards: "Estudiar con Tarjetas",
    cardOf: "Tarjeta {current} de {total}",
    flip: "Voltear",
    createYourQuiz: "Crea Tu Cuestionario",
    enableTimer: "Activar Temporizador por Pregunta",
    welcomeTitle: "Bienvenido a AI Quiz Generator Pro",
    welcomeFeature1Title: "Sube Cualquier Documento",
    welcomeFeature1Desc: "Usa archivos de texto, hojas de cálculo o incluso imágenes. Nuestra IA analizará el contenido y creará preguntas.",
    welcomeFeature2Title: "Guarda y Organiza",
    welcomeFeature2Desc: "Mantén tus preguntas favoritas guardadas para más tarde y expórtalas en formato PDF o Excel en cualquier momento.",
    welcomeFeature3Title: "Sigue Tu Progreso",
    welcomeFeature3Desc: "Revisa tu historial de cuestionarios, ve resultados detallados y repite los cuestionarios para mejorar tus conocimientos.",
    resumeQuizTitle: "¿Continuar Cuestionario?",
    resumeQuizText: "Tienes un cuestionario en progreso. ¿Quieres continuar donde lo dejaste?",
    continueQuiz: "Continuar Cuestionario",
    abandonQuiz: "Abandonar y Empezar de Nuevo",
    statistics: "Estadísticas",
    interfaceSettings: "Configuración de Interfaz",
    themeColor: "Color del Tema",
    appearance: "Apariencia",
    light: "Claro",
    dark: "Oscuro",
    settings: "Ajustes",
    noStatistics: "Completa un cuestionario para ver tus estadísticas aquí.",
    overallPerformance: "Rendimento General",
    averageScore: "Puntuación Media",
    quizzesCompleted: "Cuestionarios Completados",
    performanceByDifficulty: "Rendimiento por Dificultad",
    quizCompletionTrend: "Tendencia de Finalización",
    quizzesPerMonth: "Cuestionarios por mes (últimos 6)",
    createManuallyTitle: "O usa un prompt personalizado",
    createManuallyDesc: "Copia el siguiente prompt para generar preguntas con un formato de columnas específico. Pégalo en tu documento y súbelo, o úsalo en tu herramienta de IA preferida.",
    copyPrompt: "Copiar Prompt",
    copied: "¡Copiado!",
    promptToCopy: "GENERAME PREGUNTAS CON FORMATO DE TABLA CON COLUMNAS: Pregunta, Opcion1, Opcion2, Opcion3, Opcion4, IndiceRespuestaCorrecta (0-3), Justificación",
    status: "Estado",
    completed: "Completado",
    inProgress: "En Progreso",
    downloadBackupExcel: "Descargar Respaldo (Excel)",
    summary: "Resumen",
    result: "Resultado",
    regenerate: "Regenerar",
    selectExplanationStyle: "Seleccionar Estilo de Explicación",
    [ExplanationStyle.Tecnica]: "Técnica",
    [ExplanationStyle.Cientifica]: "Científica",
    [ExplanationStyle.Academica]: "Académica",
    [ExplanationStyle.Didactica]: "Didáctica o pedagógica",
    [ExplanationStyle.Analitica]: "Analítica",
    [ExplanationStyle.Comparativa]: "Comparativa",
    [ExplanationStyle.Practica]: "Práctica o aplicada",
    [ExplanationStyle.Descriptiva]: "Descriptiva",
    [ExplanationStyle.Causal]: "Causal",
    [ExplanationStyle.Funcional]: "Funcional",
    [ExplanationStyle.Teleologica]: "Teleológica (por finalidad)",
    [ExplanationStyle.Historica]: "Histórica",
    [ExplanationStyle.Filosofica]: "Filosófica",
    quizMode: "Modo de Cuestionario",
    MultipleChoice: "Opción Múltiple",
    Written: "Respuesta Escrita",
    submitAnswer: "Enviar Respuesta",
    aiGrading: "Calificando con IA...",
    yourWrittenAnswer: "Tu Respuesta Escrita",
    aiFeedback: "Comentarios de la IA",
    similarityScore: "Puntaje de Similitud",
    correctAnswerText: "Respuesta Correcta de Referencia",
    specificInstructions: "Instrucciones Específicas",
    optional: "Opcional",
    promptPlaceholder: "Ej: Enfócate en el capítulo 3, crea preguntas sobre el contexto histórico...",
    selectAll: "Seleccionar todo",
    itemsSelected: "{count} elementos seleccionados",
    deleteSelected: "Eliminar seleccionados",
    confirmDeleteSelected: "¿Estás seguro de que quieres eliminar {count} cuestionarios seleccionados? Esta acción no se puede deshacer.",
    saveExplanation: "Guardar Explicación",
    explanationSaved: "¡Guardada!",
    explanationColumn: "Explicación {n}",
  }
};